// Use a default clothing image as placeholder
const placeholderImage = require("@/assets/images/shirt.jpg");

export const dummyWardrobe = [
  {
    id: 1,
    name: "Classic T-Shirt",
    category: "tops",
    color: "white",
    size: "M",
    description: "A comfortable white t-shirt",
    image: require("@/assets/images/shirt.jpg"),
  },
  {
    id: 2,
    name: "Blue Jeans",
    category: "bottoms",
    color: "blue",
    size: "L",
    description: "Classic blue denim jeans",
    image: require("@/assets/images/jeans.jpg"),
  },
  {
    id: 3,
    name: "Black Sneakers",
    category: "shoes",
    color: "black",
    size: "10",
    description: "Comfortable black sneakers",
    image: require("@/assets/images/shoes.jpg"),
  },
  {
    id: 4,
    name: "White Button-Up",
    category: "tops",
    color: "white",
    size: "M",
    description: "Crisp white button-up shirt",
    image: require("@/assets/images/shirt.jpg"),
  },
  {
    id: 5,
    name: "Dark Jeans",
    category: "bottoms",
    color: "black",
    size: "L",
    description: "Slim fit dark jeans",
    image: require("@/assets/images/jeans1.jpg"),
  },
  {
    id: 6,
    name: "Brown Boots",
    category: "shoes",
    color: "brown",
    size: "10",
    description: "Leather brown boots",
    image: require("@/assets/images/shoes1.jpg"),
  },
  {
    id: 7,
    name: "Casual Outfit",
    category: "outfits",
    color: "mixed",
    size: "M",
    description: "Complete casual outfit",
    image: require("@/assets/images/outfit.jpg"),
  },
  {
    id: 8,
    name: "White Sneakers",
    category: "shoes",
    color: "white",
    size: "10",
    description: "Clean white sneakers",
    image: require("@/assets/images/shoes2.jpg"),
  },
  {
    id: 9,
    name: "Denim Jacket",
    category: "tops",
    color: "blue",
    size: "L",
    description: "Classic denim jacket",
    image: placeholderImage,
  },
  {
    id: 10,
    name: "Black Pants",
    category: "bottoms",
    color: "black",
    size: "M",
    description: "Formal black pants",
    image: placeholderImage,
  },
  {
    id: 11,
    name: "Hoodie",
    category: "tops",
    color: "gray",
    size: "L",
    description: "Comfortable gray hoodie",
    image: placeholderImage,
  },
  {
    id: 12,
    name: "Summer Dress",
    category: "dresses",
    color: "floral",
    size: "M",
    description: "Light floral summer dress",
    image: placeholderImage,
  },
  {
    id: 13,
    name: "Blazer",
    category: "tops",
    color: "navy",
    size: "L",
    description: "Professional navy blazer",
    image: placeholderImage,
  },
  {
    id: 14,
    name: "Shorts",
    category: "bottoms",
    color: "khaki",
    size: "M",
    description: "Casual khaki shorts",
    image: placeholderImage,
  },
  {
    id: 15,
    name: "Sandals",
    category: "shoes",
    color: "brown",
    size: "9",
    description: "Leather sandals",
    image: placeholderImage,
  },
  {
    id: 16,
    name: "Scarf",
    category: "accessories",
    color: "red",
    size: "One Size",
    description: "Silk red scarf",
    image: placeholderImage,
  },
];
